### ISSUE TITLE
Error with github provider (october 2024)

### ISSUE THREAD

**Issue by aeltorio** [sctg-development/sctgdesk-api-server#16]
in October 2024 Github provider generates an error with:  
```toml
[[provider]]
provider = "Github"
authorization_url = "https://github.com/login/oauth/authorize"
token_exchange_url = "https://github.com/login/oauth/access_token"
app_id = "Ovxxxxxxxxxxxxxxxx"
app_secret = "41axxxxxxxxxxxxxxxxxxxxxx"
scope = "read:user user:email"
op_auth_string = "oidc/github"
op = "github"
```
http://domain:21114/api/oidc/callback
