### ISSUE TITLE
How to change the webconsole administrator user password?

### ISSUE THREAD

**Issue by Zerorigin** [sctg-development/sctgdesk-api-server#4]
The same as title.

**Comment by VenimK** [comment]
Jus create new user @Zerorigin  
/ui/index
Users

**Comment by aeltorio** [comment]
@Zerorigin, thank you for your interest in this project!

As @VenimK mentioned, to change the admin password:

1. Log in to the web console using the original admin password (`Hello,world!`)
2. Navigate to the `Users` tab
3. Click the `Edit` button corresponding to the user you want to modify

For your convenience, I've added two new Wiki pages:

1. [How to Change Admin or Other User Password](https://github.com/sctg-development/sctgdesk-server/wiki/Change-admin-or-other-user-password)
2. [How to Recover a Lost Password](https://github.com/sctg-development/sctgdesk-server/wiki/Troubleshooting#faq)

These pages provide detailed instructions for managing user passwords, including recovery procedures.

If you have any further questions, please don't hesitate to ask. We're here to help!

**Comment by Zerorigin** [comment]
There seems to be some unknown error.

![image](https://github.com/sctg-development/sctgdesk-api-server/assets/36463444/c84d0410-5743-4cf7-989f-669ecb124d7d)

```
docker network create \
  --driver=bridge \
  --subnet=172.31.0.0/16 \
  --ip-range=172.31.0.0/16 \
  --gateway=172.31.255.254 \
  br-docker
```
```
# version: '3'
networks:
  br-docker:
    external: true

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21114:21114
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    image: sctg/sctgdesk-server:latest
    command: hbbs -r hbbr.docker.local:21117
    volumes:
      - ./data:/usr/local/share/sctgdesk

    networks:
      br-docker:
        aliases:
          - hbbs.docker.local
        ipv4_address: "172.31.255.171"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    image: sctg/sctgdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/usr/local/share/sctgdesk
    networks:
      br-docker:
        aliases:
          - hbbr.docker.local
        ipv4_address: "172.31.255.172"

    restart: unless-stopped
```
